### ISSUE TITLE
Ghost From The Past scenario is somehow broken

### ISSUE THREAD

**Issue by RayvenMaker** [Team-Automata/EmptyEpsilon-scripts#2]
We might've accidentally overwritten one of the ships or artifacts used.

**Comment by Team-Automata** [comment]
The Ktlitan ships it uses are in the shipTemplates_OLD file.  I was planning to move them to a new file at some point so that file is not in use.

**Comment by RayvenMaker** [comment]
Alright. We should probably make that it's own class file. I'll see if I can get on it...

**Comment by RayvenMaker** [comment]
Just committed the changes. It works now!
